pj.step <- function(dat, l.mean, proj, n.search, kn){
  n.data <- nrow(dat)
  proj <- data.frame(proj)
  names(proj) <- c('X1')
  x.gam <- gam(l.mean[,1]~s(X1,k=kn,m=2), data=proj, method="REML")
  y.gam <- gam(l.mean[,2]~s(X1,k=kn,m=2), data=proj, method="REML")
  grid.x <- data.frame(seq(0, 1, length.out=(n.search)))
  names(grid.x) <- c("X1")
  x.pred <- predict(x.gam, grid.x)
  y.pred <- predict(y.gam, grid.x)
  grid.fit <- cbind(x.pred, y.pred)
  x.p <- rep(0, times=n.data)
  new <- apply(dat, 1, function(x){which.min(colSums((t(grid.fit)-x)^2))})
  x.p <- (new-1)/(n.search-1)
  projn <- data.frame(x.p)
  names(projn) <- c("X1")
  x.fitted <- predict(x.gam, projn)
  y.fitted <- predict(y.gam, projn)
  data.fit <- cbind(x.fitted, y.fitted)
  pj.step <- list(proj=as.matrix(projn), prin.curve=grid.fit, curve.x=x.gam, curve.y=y.gam)
}